export enum MsgEvent{

    OP_TOUCH_MOVE = "OP_TOUCH_MOVE",
    OP_TOUCH_SCALE = "OP_TOUCH_SCALE",
    OP_TOUCH_ROTA = "OP_TOUCH_ROTA",
    OP_TOUCH_START = "OP_TOUCH_START",
    OP_TOUCH_UP = "OP_TOUCH_UP",
    OP_TOUCH_MOVE_MAP = "OP_TOUCH_MOVE_MAP",
}